# Generated by Django 2.2.7 on 2019-11-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavefunction', '0002_auto_20191107_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadron',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the interpolating operator', null=True),
        ),
        migrations.AlterField(
            model_name='hadron',
            name='embedding',
            field=models.PositiveSmallIntegerField(help_text='k-th embedding of O^D_h irrep.'),
        ),
        migrations.AlterField(
            model_name='hadron',
            name='irrep',
            field=models.TextField(help_text='Irreducible representations of O^D_h (octahedral group)'),
        ),
        migrations.AlterField(
            model_name='hadron',
            name='isospin_x2',
            field=models.PositiveSmallIntegerField(help_text='Total isospin times 2'),
        ),
        migrations.AlterField(
            model_name='hadron',
            name='isospin_z_x2',
            field=models.SmallIntegerField(help_text='Isospin in \\(z\\)-direction times 2'),
        ),
        migrations.AlterField(
            model_name='hadron',
            name='momentum',
            field=models.SmallIntegerField(help_text='Momentum in units of 2 pi / L'),
        ),
        migrations.AlterField(
            model_name='hadron',
            name='parity',
            field=models.SmallIntegerField(help_text='Parity of hadronic operator'),
        ),
        migrations.AlterField(
            model_name='hadron',
            name='spin_x2',
            field=models.PositiveSmallIntegerField(help_text='Total spin times 2'),
        ),
        migrations.AlterField(
            model_name='hadron',
            name='spin_z_x2',
            field=models.SmallIntegerField(help_text='Spin in \\(z\\)-direction'),
        ),
        migrations.AlterField(
            model_name='hadron',
            name='strangeness',
            field=models.PositiveSmallIntegerField(help_text='Strangeness of hadronic operator'),
        ),
        migrations.AlterField(
            model_name='hadron4d',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the interpolating operator', null=True),
        ),
        migrations.AlterField(
            model_name='hadron4d',
            name='embedding',
            field=models.PositiveSmallIntegerField(help_text='k-th embedding of O^D_h irrep.'),
        ),
        migrations.AlterField(
            model_name='hadron4d',
            name='irrep',
            field=models.TextField(help_text='Irreducible representations of O^D_h (octahedral group)'),
        ),
        migrations.AlterField(
            model_name='hadron4d',
            name='isospin_x2',
            field=models.PositiveSmallIntegerField(help_text='Total isospin times 2'),
        ),
        migrations.AlterField(
            model_name='hadron4d',
            name='isospin_z_x2',
            field=models.SmallIntegerField(help_text='Isospin in \\(z\\)-direction times 2'),
        ),
        migrations.AlterField(
            model_name='hadron4d',
            name='parity',
            field=models.SmallIntegerField(help_text='Parity of hadronic operator'),
        ),
        migrations.AlterField(
            model_name='hadron4d',
            name='spin_x2',
            field=models.PositiveSmallIntegerField(help_text='Total spin times 2'),
        ),
        migrations.AlterField(
            model_name='hadron4d',
            name='spin_z_x2',
            field=models.SmallIntegerField(help_text='Spin in \\(z\\)-direction times 2'),
        ),
        migrations.AlterField(
            model_name='hadron4d',
            name='strangeness',
            field=models.PositiveSmallIntegerField(help_text='Strangeness of hadronic operator'),
        ),
    ]
