# Generated by Django 2.2.7 on 2019-11-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavefunction', '0003_auto_20191119_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadron',
            name='embedding',
            field=models.PositiveSmallIntegerField(blank=True, help_text='k-th embedding of O^D_h irrep., can be blank'),
        ),
    ]
