# Generated by Django 2.2.7 on 2020-02-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavefunction', '0005_remove_scswavefunction_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hadron',
            name='unique_hadron_hadron',
        ),
        migrations.RenameField(
            model_name='hadron',
            old_name='momentum',
            new_name='nx',
        ),
        migrations.AddField(
            model_name='hadron',
            name='ny',
            field=models.SmallIntegerField(default=0, help_text='Momentum in units of 2 pi / L'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hadron',
            name='nz',
            field=models.SmallIntegerField(default=0, help_text='Momentum in units of 2 pi / L'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='hadron',
            constraint=models.UniqueConstraint(fields=('strangeness', 'irrep', 'embedding', 'parity', 'spin_x2', 'spin_z_x2', 'isospin_x2', 'isospin_z_x2', 'nx', 'ny', 'nz'), name='unique_hadron_hadron'),
        ),
    ]
