SECRET_KEY: s5icy)=l+((ds60p!+)ypf@8!ey))bb^(mf0v(0&kd=ut!xfbu
PROJECT_APPS:
    - lattedb.status
    - lattedb.fermionaction
    - lattedb.gaugeaction
    - lattedb.gaugeconfig
    - lattedb.linksmear
    - lattedb.propagator
    - lattedb.wavefunction
    - lattedb.quarksmear
    - lattedb.current
    - lattedb.correlator
    - lattedb.ensemble
    - lattedb.project.ga_q2
    - lattedb.project.fhcompare
ALLOWED_HOSTS:
    - 127.0.0.1
    - ithems.lbl.gov
DEBUG: True
