# Generated by Django 2.2.7 on 2019-11-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensemble', '0002_auto_20191107_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensemble',
            name='label',
            field=models.CharField(help_text='Label to identify ensemble for easy searches', max_length=40, unique=True),
        ),
    ]
