# Generated by Django 2.2.7 on 2019-11-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensemble', '0003_auto_20191119_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensemble',
            name='configurations',
            field=models.ManyToManyField(help_text='Set of Foreign Keys to gauge configurations which together defines an ensemble', to='gaugeconfig.GaugeConfig'),
        ),
    ]
