# Generated by Django 2.2.7 on 2019-11-19 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fermionaction', '0002_auto_20191107_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisq',
            name='linksmear',
            field=models.ForeignKey(help_text='Foreign Key pointing to additional gauge \\(\\texttt{linksmear}\\) outside of Monte Carlo.', on_delete=django.db.models.deletion.CASCADE, to='linksmear.LinkSmear'),
        ),
        migrations.AlterField(
            model_name='hisq',
            name='naik',
            field=models.DecimalField(decimal_places=6, help_text='Coefficient of Naik term. If Naik term is not included, explicitly set to 0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='hisq',
            name='quark_mass',
            field=models.DecimalField(decimal_places=6, help_text='Input quark mass', max_digits=10),
        ),
        migrations.AlterField(
            model_name='hisq',
            name='quark_tag',
            field=models.TextField(help_text='Type of quark'),
        ),
        migrations.AlterField(
            model_name='mobiusdw',
            name='b5',
            field=models.DecimalField(decimal_places=6, help_text='Mobius kernel parameter [a5 = b5 - c5, alpha5 * a5 = b5 + c5]', max_digits=10),
        ),
        migrations.AlterField(
            model_name='mobiusdw',
            name='c5',
            field=models.DecimalField(decimal_places=6, help_text='Mobius kernal perameter', max_digits=10),
        ),
        migrations.AlterField(
            model_name='mobiusdw',
            name='l5',
            field=models.PositiveSmallIntegerField(help_text='Length of 5th dimension'),
        ),
        migrations.AlterField(
            model_name='mobiusdw',
            name='linksmear',
            field=models.ForeignKey(help_text='Foreign Key pointing to additional gauge \\(\\texttt{linksmear}\\) outside of Monte Carlo.', on_delete=django.db.models.deletion.CASCADE, to='linksmear.LinkSmear'),
        ),
        migrations.AlterField(
            model_name='mobiusdw',
            name='m5',
            field=models.DecimalField(decimal_places=6, help_text='5th dimensional mass', max_digits=10),
        ),
        migrations.AlterField(
            model_name='mobiusdw',
            name='quark_mass',
            field=models.DecimalField(decimal_places=6, help_text='Input quark mass', max_digits=10),
        ),
        migrations.AlterField(
            model_name='mobiusdw',
            name='quark_tag',
            field=models.TextField(help_text='Type of quark'),
        ),
    ]
