# Generated by Django 2.2.7 on 2019-11-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fermionaction', '0003_auto_20191119_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisq',
            name='linksmear',
            field=models.ForeignKey(help_text='Foreign Key pointing to additional gauge `linksmear` outside of Monte Carlo.', on_delete=django.db.models.deletion.CASCADE, to='linksmear.LinkSmear'),
        ),
        migrations.AlterField(
            model_name='mobiusdw',
            name='linksmear',
            field=models.ForeignKey(help_text='Foreign Key pointing to additional gauge `linksmear` outside of Monte Carlo.', on_delete=django.db.models.deletion.CASCADE, to='linksmear.LinkSmear'),
        ),
    ]
