# Generated by Django 2.2.7 on 2019-11-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaugeaction', '0002_auto_20191107_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luescherweisz',
            name='a_fm',
            field=models.DecimalField(decimal_places=6, help_text='Lattice spacing in fermi', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='luescherweisz',
            name='beta',
            field=models.DecimalField(decimal_places=6, help_text='Strong coupling constant', max_digits=10),
        ),
        migrations.AlterField(
            model_name='luescherweisz',
            name='u0',
            field=models.DecimalField(decimal_places=6, help_text='Tadpole improvement coefficient', max_digits=10),
        ),
    ]
