# Generated by Django 2.2.7 on 2019-11-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0002_auto_20191107_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='description',
            field=models.TextField(blank=True, help_text='Description of current', null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='diracstruct',
            field=models.TextField(help_text='Dirac structure of the current'),
        ),
        migrations.AlterField(
            model_name='local',
            name='momentum',
            field=models.SmallIntegerField(help_text='Current insertion momentum in units of 2 pi / L'),
        ),
        migrations.AlterField(
            model_name='local4d',
            name='description',
            field=models.TextField(blank=True, help_text='Description of current', null=True),
        ),
        migrations.AlterField(
            model_name='local4d',
            name='diracstruct',
            field=models.TextField(help_text='Dirac structure of the current'),
        ),
    ]
