# Generated by Django 2.2.5 on 2019-11-22 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0003_auto_20191119_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current',
            name='type',
        ),
    ]
