# Generated by Django 2.2.7 on 2020-02-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0004_remove_current_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='local',
            name='unique_current_local',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='momentum',
            new_name='nx',
        ),
        migrations.AddField(
            model_name='local',
            name='ny',
            field=models.SmallIntegerField(default=0, help_text='Current insertion momentum in units of 2 pi / L'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='local',
            name='nz',
            field=models.SmallIntegerField(default=0, help_text='Current insertion momentum in units of 2 pi / L'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='local',
            constraint=models.UniqueConstraint(fields=('diracstruct', 'nx', 'ny', 'nz'), name='unique_current_local'),
        ),
    ]
