# Generated by Django 2.2.5 on 2019-10-30 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correlator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baryon2pt',
            fields=[
                ('id', models.AutoField(help_text='Primary key for Base class.', primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False, help_text='Type for the base class. Will be auto set to specialized type on save')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date the class was last modified')),
                ('tag', models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=20, null=True)),
                ('home', models.TextField(blank=True, help_text='(Optional) Text: Computing facility where the object resides at', null=True)),
                ('file_path', models.TextField(blank=True, help_text='(Optional) Text: Path to hdf5 file', null=True)),
                ('dset_path', models.TextField(blank=True, help_text='(Optional) Text: Path to dset in hdf5 file', null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Unknown'), (1, 'Does not exist'), (2, 'Exists'), (3, 'On tape')], help_text='PositiveSmallInt: Encode categorical status labels', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='DateTime:Last time the field was updated.')),
                ('source_group', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: Index to the source group', null=True)),
                ('baryon2pt', models.ForeignKey(help_text='ForeignKey: Baryon two point correlation function', on_delete=django.db.models.deletion.CASCADE, to='correlator.Baryon2pt')),
                ('user', models.ForeignKey(blank=True, help_text='User who updated this object. Set on save by connection to database. Ananymous if not found.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='baryon2pt',
            constraint=models.UniqueConstraint(fields=('baryon2pt', 'home'), name='unique_baryon2pt_file_status'),
        ),
    ]
