# Generated by Django 2.2.8 on 2020-01-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20191107_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baryon2pt',
            name='type',
        ),
    ]
