# Generated by Django 2.2.6 on 2019-11-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_fhcompare', '0005_auto_20191016_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fhcompare',
            name='tag',
            field=models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sourceavg2pt',
            name='tag',
            field=models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=200, null=True),
        ),
    ]
