# Generated by Django 2.2.5 on 2019-10-30 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fermionaction', '0001_initial'),
        ('quarksmear', '0001_initial'),
        ('gaugeconfig', '0001_initial'),
        ('current', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wavefunction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propagator',
            fields=[
                ('id', models.AutoField(help_text='Primary key for Base class.', primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False, help_text='Type for the base class. Will be auto set to specialized type on save')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date the class was last modified')),
                ('tag', models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who updated this object. Set on save by connection to database. Ananymous if not found.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OneToAll',
            fields=[
                ('propagator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propagator.Propagator')),
                ('origin_x', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: x-coordinate origin location of the propagator')),
                ('origin_y', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: y-coordinate origin location of the propagator')),
                ('origin_z', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: z-coordinate origin location of the propagator')),
                ('origin_t', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: t-coordinate origin location of the propagator')),
                ('fermionaction', models.ForeignKey(help_text='ForeignKey pointing to valence lattice fermion action. This is the valence action.', on_delete=django.db.models.deletion.CASCADE, to='fermionaction.FermionAction')),
                ('gaugeconfig', models.ForeignKey(help_text='ForeignKey pointing to specific gauge configuration inverted on', on_delete=django.db.models.deletion.CASCADE, to='gaugeconfig.GaugeConfig')),
                ('sinksmear', models.ForeignKey(help_text='ForeignKey pointing to sink quark smearing', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear')),
                ('sourcesmear', models.ForeignKey(help_text='ForeignKey pointing to source quark smearing', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear')),
            ],
            bases=('propagator.propagator',),
        ),
        migrations.CreateModel(
            name='FeynmanHellmann',
            fields=[
                ('propagator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propagator.Propagator')),
                ('current', models.ForeignKey(help_text='ForeignKey linking momentum space current insertion', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='current.Current')),
                ('fermionaction', models.ForeignKey(help_text='ForeignKey pointing to valence lattice fermion action', on_delete=django.db.models.deletion.CASCADE, to='fermionaction.FermionAction')),
                ('gaugeconfig', models.ForeignKey(help_text='ForeignKey pointing to specific gauge configuration inverted on', on_delete=django.db.models.deletion.CASCADE, to='gaugeconfig.GaugeConfig')),
                ('propagator', models.ForeignKey(help_text='ForeignKey linking RHS propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('sinksmear', models.ForeignKey(help_text='ForeignKey pointing to sink quark smearing', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear')),
                ('sourcesmear', models.ForeignKey(help_text='ForeignKey pointing to source quark smearing', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear')),
            ],
            bases=('propagator.propagator',),
        ),
        migrations.CreateModel(
            name='BaryonCoherentSeq',
            fields=[
                ('propagator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propagator.Propagator')),
                ('groupsize', models.PositiveSmallIntegerField(help_text='PositiveSmallint: Total number of propagators sharing a coherent sink')),
                ('groupindex', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: A group index indicating which coherent sink group the propagator belongs to')),
                ('sinksep', models.SmallIntegerField(help_text='SmallInt: Source-sink separation time')),
                ('fermionaction', models.ForeignKey(help_text='ForeignKey pointing to valence lattice fermion action', on_delete=django.db.models.deletion.CASCADE, to='fermionaction.FermionAction')),
                ('gaugeconfig', models.ForeignKey(help_text='ForeignKey pointing to specific gauge configuration inverted on', on_delete=django.db.models.deletion.CASCADE, to='gaugeconfig.GaugeConfig')),
                ('propagator0', models.ForeignKey(help_text='ForeignKey that link to a coherent propagator (spectator 0)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('propagator1', models.ForeignKey(help_text='ForeignKey that link to a coherent propagator (spectator 1)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('sinksmear', models.ForeignKey(help_text='ForeignKey pointing to sink quark smearing', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear')),
                ('sinkwave', models.ForeignKey(help_text='ForeignKey: Pointer to sink interpolating operator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction')),
                ('sourcesmear', models.ForeignKey(help_text='ForeignKey pointing to source quark smearing', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear')),
            ],
            bases=('propagator.propagator',),
        ),
        migrations.AddConstraint(
            model_name='onetoall',
            constraint=models.UniqueConstraint(fields=('gaugeconfig', 'fermionaction', 'origin_x', 'origin_y', 'origin_z', 'origin_t', 'sourcesmear', 'sinksmear'), name='unique_propagator_onetoall'),
        ),
        migrations.AddConstraint(
            model_name='feynmanhellmann',
            constraint=models.UniqueConstraint(fields=('gaugeconfig', 'fermionaction', 'propagator', 'current', 'sourcesmear', 'sinksmear'), name='unique_propagator_feynmanhellmann'),
        ),
        migrations.AddConstraint(
            model_name='baryoncoherentseq',
            constraint=models.UniqueConstraint(fields=('gaugeconfig', 'fermionaction', 'propagator0', 'propagator1', 'groupsize', 'groupindex', 'sourcesmear', 'sinksmear', 'sinkwave', 'sinksep'), name='unique_propagator_coherentseq'),
        ),
    ]
