# Generated by Django 2.2.5 on 2019-11-22 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propagator', '0002_auto_20191122_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propagator',
            name='type',
        ),
    ]
