# Generated by Django 2.2.7 on 2019-11-19 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propagator', '0002_auto_20191107_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='fermionaction',
            field=models.ForeignKey(help_text='Foreign Key referencing valence lattice \\(\\texttt{fermionaction}\\)', on_delete=django.db.models.deletion.CASCADE, to='fermionaction.FermionAction'),
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='gaugeconfig',
            field=models.ForeignKey(help_text='Foreign Key referencing specific \\(\\texttt{gaugeconfig}\\) inverted on', on_delete=django.db.models.deletion.CASCADE, to='gaugeconfig.GaugeConfig'),
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='groupindex',
            field=models.PositiveSmallIntegerField(help_text='Group index indicating which coherent sink group the propagator belongs to'),
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='groupsize',
            field=models.PositiveSmallIntegerField(help_text='Total number of propagators sharing a coherent sink'),
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='propagator0',
            field=models.ForeignKey(help_text='Foreign Key referencing OneToAll \\(\\texttt{propagator}\\) (spectator 0)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='propagator1',
            field=models.ForeignKey(help_text='Foreign Key referencing OneToAll \\(\\texttt{propagator}\\) (spectator 1)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='sinksep',
            field=models.SmallIntegerField(help_text='Source-sink separation time'),
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='sinksmear',
            field=models.ForeignKey(help_text='Foreign Key referencing sink \\(\\texttt{quarksmear}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear'),
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='sinkwave',
            field=models.ForeignKey(help_text='Foreign Key referencing sink interpolating operator \\(\\texttt{wavefunction}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='sourcesmear',
            field=models.ForeignKey(help_text='Foreign Key referencing source \\(\\texttt{quarksmear}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear'),
        ),
        migrations.AlterField(
            model_name='feynmanhellmann',
            name='current',
            field=models.ForeignKey(help_text='Foreign Key linking momentum space \\(\\texttt{current}\\) insertion', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='current.Current'),
        ),
        migrations.AlterField(
            model_name='feynmanhellmann',
            name='fermionaction',
            field=models.ForeignKey(help_text='Foreign Key pointing to valence lattice \\(\\texttt{fermionaction}\\)', on_delete=django.db.models.deletion.CASCADE, to='fermionaction.FermionAction'),
        ),
        migrations.AlterField(
            model_name='feynmanhellmann',
            name='gaugeconfig',
            field=models.ForeignKey(help_text='Foreign Key pointing to specific \\(\\texttt{gaugeconfig}\\) inverted on', on_delete=django.db.models.deletion.CASCADE, to='gaugeconfig.GaugeConfig'),
        ),
        migrations.AlterField(
            model_name='feynmanhellmann',
            name='propagator',
            field=models.ForeignKey(help_text='Foreign Key linking RHS OneToAll \\(\\texttt{propagator}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='feynmanhellmann',
            name='sinksmear',
            field=models.ForeignKey(help_text='Foreign Key pointing to sink \\(\\texttt{quarksmear}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear'),
        ),
        migrations.AlterField(
            model_name='feynmanhellmann',
            name='sourcesmear',
            field=models.ForeignKey(help_text='Foreign Key pointing to source \\(\\texttt{quarksmear}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear'),
        ),
        migrations.AlterField(
            model_name='onetoall',
            name='fermionaction',
            field=models.ForeignKey(help_text='Foreign Key pointing to valence lattice \\(\\texttt{fermionaction}\\). This is the valence action.', on_delete=django.db.models.deletion.CASCADE, to='fermionaction.FermionAction'),
        ),
        migrations.AlterField(
            model_name='onetoall',
            name='gaugeconfig',
            field=models.ForeignKey(help_text='Foreign Key pointing to specific \\texttt{gaugeconfig} inverted on', on_delete=django.db.models.deletion.CASCADE, to='gaugeconfig.GaugeConfig'),
        ),
        migrations.AlterField(
            model_name='onetoall',
            name='origin_t',
            field=models.PositiveSmallIntegerField(help_text='t-coordinate origin location of the propagator'),
        ),
        migrations.AlterField(
            model_name='onetoall',
            name='origin_x',
            field=models.PositiveSmallIntegerField(help_text='x-coordinate origin location of the propagator'),
        ),
        migrations.AlterField(
            model_name='onetoall',
            name='origin_y',
            field=models.PositiveSmallIntegerField(help_text='y-coordinate origin location of the propagator'),
        ),
        migrations.AlterField(
            model_name='onetoall',
            name='origin_z',
            field=models.PositiveSmallIntegerField(help_text='z-coordinate origin location of the propagator'),
        ),
        migrations.AlterField(
            model_name='onetoall',
            name='sinksmear',
            field=models.ForeignKey(help_text='Foreign Key pointing to sink \\(\\texttt{quarksmear}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear'),
        ),
        migrations.AlterField(
            model_name='onetoall',
            name='sourcesmear',
            field=models.ForeignKey(help_text='Foreign Key pointing to source \\(\\texttt{quarksmear}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear'),
        ),
    ]
