# Generated by Django 2.2.2 on 2019-10-21 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propagator', '0002_auto_20191016_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetoall',
            name='fermionaction',
            field=models.ForeignKey(help_text='ForeignKey pointing to valence lattice fermion action. This is the valence action.', on_delete=django.db.models.deletion.CASCADE, to='fermionaction.FermionAction'),
        ),
    ]
