# Generated by Django 2.2.5 on 2019-11-23 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propagator', '0003_remove_propagator_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feynmanhellmann',
            name='unique_propagator_feynmanhellmann',
        ),
        migrations.RemoveField(
            model_name='feynmanhellmann',
            name='sourcesmear',
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='sinksmear',
            field=models.ForeignKey(help_text='Foreign Key pointing to sink `quarksmear` which should be Point unless some bizarre calculation', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear'),
        ),
        migrations.AddConstraint(
            model_name='feynmanhellmann',
            constraint=models.UniqueConstraint(fields=('gaugeconfig', 'fermionaction', 'propagator', 'current', 'sinksmear'), name='unique_propagator_feynmanhellmann'),
        ),
    ]
