# Generated by Django 2.2.7 on 2019-11-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propagator', '0003_auto_20191119_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='fermionaction',
            field=models.ForeignKey(help_text='Foreign Key referencing valence lattice `fermionaction`', on_delete=django.db.models.deletion.CASCADE, to='fermionaction.FermionAction'),
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='gaugeconfig',
            field=models.ForeignKey(help_text='Foreign Key referencing specific `gaugeconfig` inverted on', on_delete=django.db.models.deletion.CASCADE, to='gaugeconfig.GaugeConfig'),
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='propagator0',
            field=models.ForeignKey(help_text='Foreign Key referencing OneToAll `propagator` (spectator 0)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='propagator1',
            field=models.ForeignKey(help_text='Foreign Key referencing OneToAll `propagator` (spectator 1)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='sinksmear',
            field=models.ForeignKey(help_text='Foreign Key referencing sink `quarksmear`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear'),
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='sinkwave',
            field=models.ForeignKey(help_text='Foreign Key referencing sink interpolating operator `wavefunction`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='sourcesmear',
            field=models.ForeignKey(help_text='Foreign Key referencing source `quarksmear`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear'),
        ),
        migrations.AlterField(
            model_name='feynmanhellmann',
            name='current',
            field=models.ForeignKey(help_text='Foreign Key linking momentum space `current` insertion', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='current.Current'),
        ),
        migrations.AlterField(
            model_name='feynmanhellmann',
            name='fermionaction',
            field=models.ForeignKey(help_text='Foreign Key pointing to valence lattice `fermionaction`', on_delete=django.db.models.deletion.CASCADE, to='fermionaction.FermionAction'),
        ),
        migrations.AlterField(
            model_name='feynmanhellmann',
            name='gaugeconfig',
            field=models.ForeignKey(help_text='Foreign Key pointing to specific `gaugeconfig` inverted on', on_delete=django.db.models.deletion.CASCADE, to='gaugeconfig.GaugeConfig'),
        ),
        migrations.AlterField(
            model_name='feynmanhellmann',
            name='propagator',
            field=models.ForeignKey(help_text='Foreign Key linking RHS OneToAll `propagator`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='feynmanhellmann',
            name='sinksmear',
            field=models.ForeignKey(help_text='Foreign Key pointing to sink `quarksmear`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear'),
        ),
        migrations.AlterField(
            model_name='feynmanhellmann',
            name='sourcesmear',
            field=models.ForeignKey(help_text='Foreign Key pointing to source `quarksmear`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear'),
        ),
        migrations.AlterField(
            model_name='onetoall',
            name='fermionaction',
            field=models.ForeignKey(help_text='Foreign Key pointing to valence lattice `fermionaction`. This is the valence action.', on_delete=django.db.models.deletion.CASCADE, to='fermionaction.FermionAction'),
        ),
        migrations.AlterField(
            model_name='onetoall',
            name='sinksmear',
            field=models.ForeignKey(help_text='Foreign Key pointing to sink `quarksmear`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear'),
        ),
        migrations.AlterField(
            model_name='onetoall',
            name='sourcesmear',
            field=models.ForeignKey(help_text='Foreign Key pointing to source `quarksmear`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear'),
        ),
    ]
