# Generated by Django 2.2.7 on 2019-11-22 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propagator', '0004_auto_20191120_2024'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='baryoncoherentseq',
            name='unique_propagator_coherentseq',
        ),
        migrations.RemoveField(
            model_name='baryoncoherentseq',
            name='groupindex',
        ),
        migrations.RemoveField(
            model_name='baryoncoherentseq',
            name='groupsize',
        ),
        migrations.RemoveField(
            model_name='baryoncoherentseq',
            name='sourcesmear',
        ),
        migrations.RemoveField(
            model_name='baryoncoherentseq',
            name='propagator0',
        ),
        migrations.AddField(
            model_name='baryoncoherentseq',
            name='propagator0',
            field=models.ManyToManyField(help_text='A set of Foreign Keys referencing OneToAll `propagator` (spectator 0) in same source group', related_name='_baryoncoherentseq_propagator0_+', to='propagator.Propagator'),
        ),
        migrations.RemoveField(
            model_name='baryoncoherentseq',
            name='propagator1',
        ),
        migrations.AddField(
            model_name='baryoncoherentseq',
            name='propagator1',
            field=models.ManyToManyField(help_text='A set of Foreign Keys referencing OneToAll `propagator` (spectator 1) in same source group', related_name='_baryoncoherentseq_propagator1_+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryoncoherentseq',
            name='sinksmear',
            field=models.ForeignKey(help_text='Foreign Key pointing to sink `quarksmear`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quarksmear.QuarkSmear'),
        ),
        migrations.AddConstraint(
            model_name='baryoncoherentseq',
            constraint=models.UniqueConstraint(fields=('gaugeconfig', 'fermionaction', 'sinkwave', 'sinksmear', 'sinksep'), name='unique_propagator_baryoncoherentseq'),
        ),
    ]
