# Generated by Django 2.2.7 on 2019-11-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksmear', '0002_auto_20191107_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wilsonflow',
            name='flowstep',
            field=models.PositiveSmallIntegerField(help_text='Number of diffusion steps'),
        ),
        migrations.AlterField(
            model_name='wilsonflow',
            name='flowtime',
            field=models.DecimalField(decimal_places=6, help_text='Flow time in lattice units', max_digits=10),
        ),
    ]
