# Generated by Django 2.2.6 on 2019-10-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The group of users who are allowed to read this notification', related_name='notifications', to='auth.Group'),
        ),
    ]
