# Generated by Django 2.2.5 on 2019-10-30 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propagator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneToAllStatus',
            fields=[
                ('id', models.AutoField(help_text='Primary key for Base class.', primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False, help_text='Type for the base class. Will be auto set to specialized type on save')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date the class was last modified')),
                ('tag', models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=20, null=True)),
                ('machine', models.CharField(help_text='The machine hosting the file.', max_length=120)),
                ('file_location', models.TextField(help_text='The path to the file.')),
                ('file_size', models.PositiveIntegerField(help_text='The size of the file in Bytes.', null=True)),
                ('mtime', models.DateTimeField(help_text='The last time the file was modified.', null=True)),
                ('exists', models.BooleanField(default=False, help_text='File exists at `file_location` on `machine`')),
                ('src_set', models.CharField(help_text='The source group the file belongs to. E.g., `0-8`', max_length=40)),
                ('propagator', models.ForeignKey(help_text='The one-to-all propagator describing properties of this file.', on_delete=django.db.models.deletion.CASCADE, to='propagator.OneToAll')),
                ('user', models.ForeignKey(blank=True, help_text='User who updated this object. Set on save by connection to database. Ananymous if not found.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('propagator', 'machine', 'file_location', 'src_set')},
            },
        ),
    ]
