# Generated by Django 2.2.5 on 2019-10-30 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarkSmear',
            fields=[
                ('id', models.AutoField(help_text='Primary key for Base class.', primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False, help_text='Type for the base class. Will be auto set to specialized type on save')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date the class was last modified')),
                ('tag', models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=20, null=True)),
                ('description', models.TextField(blank=True, help_text='(Optional) Text: Description of the quark smearing operator', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who updated this object. Set on save by connection to database. Ananymous if not found.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GaugeCovariantGaussian',
            fields=[
                ('quarksmear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quarksmear.QuarkSmear')),
                ('radius', models.DecimalField(decimal_places=6, help_text='Decimal(10,6): Smearing radius in lattice units', max_digits=10)),
                ('step', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: Number of smearing steps')),
            ],
            bases=('quarksmear.quarksmear',),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('quarksmear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quarksmear.QuarkSmear')),
            ],
            options={
                'abstract': False,
            },
            bases=('quarksmear.quarksmear',),
        ),
        migrations.AddConstraint(
            model_name='gaugecovariantgaussian',
            constraint=models.UniqueConstraint(fields=('radius', 'step'), name='unique_qaurksmear_gaugecovariantgaussian'),
        ),
    ]
