# Generated by Django 2.2.6 on 2019-11-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarksmear', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarksmear',
            name='tag',
            field=models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=200, null=True),
        ),
    ]
