# Generated by Django 2.2.5 on 2019-11-22 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_formfac', '0001_squashed_0010_auto_20191111_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concatenatedformfactor4dfile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='diskconcatenatedformfactor4dfile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='diskformfactor4dfile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='disktslicedformfactor4dfile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='disktslicedsaveragedformfactor4dfile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='formfactor4dfile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tapeconcatenatedformfactor4dfile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tapetslicedsaveragedformfactor4dfile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tslicedformfactor4dfile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tslicedsaveragedformfactor4dfile',
            name='type',
        ),
    ]
