# Generated by Django 2.2.6 on 2019-11-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_formfac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskformfactor4dfile',
            name='size',
            field=models.BigIntegerField(help_text='Size of the file in Bytes.', null=True),
        ),
        migrations.AlterField(
            model_name='tapeformfactor4dfile',
            name='size',
            field=models.BigIntegerField(help_text='Size of the file in Bytes.', null=True),
        ),
    ]
