# Generated by Django 2.2.2 on 2019-11-07 19:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_formfac', '0002_auto_20191107_0152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormFactor4DFile',
            new_name='ConcatenatedFormFactor4DFile',
        ),
        migrations.RenameModel(
            old_name='DiskFormFactor4DFile',
            new_name='DiskConcatenatedFormFactor4DFile',
        ),
        migrations.RenameModel(
            old_name='TapeFormFactor4DFile',
            new_name='TapeConcatenatedFormFactor4DFile',
        ),
    ]
