# Generated by Django 2.2.2 on 2019-11-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_formfac', '0003_auto_20191107_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskconcatenatedformfactor4dfile',
            name='exists',
            field=models.BooleanField(help_text='Can the file be found `physical_file.path/physical_file.file.name`?.'),
        ),
        migrations.AlterField(
            model_name='diskconcatenatedformfactor4dfile',
            name='path',
            field=models.TextField(help_text='The directory path.'),
        ),
        migrations.AlterField(
            model_name='tapeconcatenatedformfactor4dfile',
            name='exists',
            field=models.BooleanField(help_text='Can the file be found `physical_file.path/physical_file.file.name`?.'),
        ),
        migrations.AlterField(
            model_name='tapeconcatenatedformfactor4dfile',
            name='path',
            field=models.TextField(help_text='The directory path.'),
        ),
    ]
