# Generated by Django 2.2.7 on 2020-03-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_formfac', '0004_correlatormeta_diskcorrelatorh5dset_tapecorrelatorh5dset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correlatormeta',
            old_name='type',
            new_name='corr',
        ),
        migrations.AlterUniqueTogether(
            name='correlatormeta',
            unique_together={('corr', 'configuration', 'source')},
        ),
    ]
