# Generated by Django 2.2.7 on 2020-03-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_formfac", "0005_auto_20200311_1727"),
    ]

    operations = [
        migrations.AddField(
            model_name="correlatormeta",
            name="ensemble",
            field=models.CharField(
                default="ENSEMBLE-NOT-GIVEN",
                help_text="Name of the ensemble. E.g., `a15m135XL`.",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="correlatormeta",
            name="source_set",
            field=models.CharField(
                default="SOURCE-SET-NOT-GIVEN",
                help_text="Set of sources in this file. E.g., `16-23`.",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="correlatormeta",
            name="stream",
            field=models.CharField(
                default="ST-NOT-GI",
                help_text="Name of the HMC stream, e.g., `a`.",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="correlatormeta",
            unique_together={
                ("corr", "configuration", "source", "ensemble", "stream", "source_set")
            },
        ),
    ]
