# Generated by Django 3.0.4 on 2020-03-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_formfac", "0006_auto_20200312_0050"),
    ]

    operations = [
        migrations.RenameField(
            model_name="correlatormeta", old_name="corr", new_name="correlator",
        ),
        migrations.AlterUniqueTogether(
            name="correlatormeta",
            unique_together={
                (
                    "correlator",
                    "ensemble",
                    "stream",
                    "configuration",
                    "source_set",
                    "source",
                )
            },
        ),
    ]
