# Generated by Django 2.2.2 on 2019-11-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_formfac', '0006_diskformfactor4dfile_formfactor4dfile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formfactor4dfile',
            unique_together={('ensemble', 'stream', 'source_set', 'configuration', 't_separation', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='tslicedformfactor4dfile',
            unique_together={('ensemble', 'stream', 'source_set', 'configuration', 't_separation', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='tslicedsaveragedformfactor4dfile',
            unique_together={('ensemble', 'stream', 'source_set', 'configuration', 't_separation')},
        ),
        migrations.RemoveField(
            model_name='formfactor4dfile',
            name='current',
        ),
        migrations.RemoveField(
            model_name='formfactor4dfile',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='formfactor4dfile',
            name='parity',
        ),
        migrations.RemoveField(
            model_name='formfactor4dfile',
            name='spin',
        ),
        migrations.RemoveField(
            model_name='formfactor4dfile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='tslicedformfactor4dfile',
            name='current',
        ),
        migrations.RemoveField(
            model_name='tslicedformfactor4dfile',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='tslicedformfactor4dfile',
            name='parity',
        ),
        migrations.RemoveField(
            model_name='tslicedformfactor4dfile',
            name='spin',
        ),
        migrations.RemoveField(
            model_name='tslicedformfactor4dfile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='tslicedsaveragedformfactor4dfile',
            name='current',
        ),
        migrations.RemoveField(
            model_name='tslicedsaveragedformfactor4dfile',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='tslicedsaveragedformfactor4dfile',
            name='parity',
        ),
        migrations.RemoveField(
            model_name='tslicedsaveragedformfactor4dfile',
            name='spin',
        ),
        migrations.RemoveField(
            model_name='tslicedsaveragedformfactor4dfile',
            name='state',
        ),
    ]
