# Generated by Django 2.2.7 on 2019-11-11 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_formfac', '0007_auto_20191107_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfactor4dfile',
            name='dependent',
            field=models.OneToOneField(help_text='Link to t-sliced form factor file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependency', to='project_formfac.TSlicedFormFactor4DFile'),
        ),
    ]
