# Generated by Django 3.0.4 on 2020-04-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_formfac', '0007_auto_20200313_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlatormeta',
            name='correlator',
            field=models.CharField(choices=[('res_phi_ll', 'Residual quark mass and connected pion-like meson correlators for quark mass m_l'), ('res_phi_ss', 'Residual quark mass and connected pion-like meson correlators for quark mass m_s'), ('spec', 'Pi+, proton, proton np'), ('ff', 'Form Factor of proton for MANY currents'), ('h_spec', 'Hyperon Spectrum')], help_text='Type of the correlator.', max_length=20),
        ),
    ]
