# Generated by Django 2.2.7 on 2019-11-11 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_formfac', '0009_tslicedformfactor4dfile_dependent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskconcatenatedformfactor4dfile',
            name='file',
            field=models.OneToOneField(help_text='The file meta information.', on_delete=django.db.models.deletion.CASCADE, related_name='disk', to='project_formfac.ConcatenatedFormFactor4DFile'),
        ),
        migrations.AlterField(
            model_name='diskformfactor4dfile',
            name='file',
            field=models.OneToOneField(help_text='The file meta information.', on_delete=django.db.models.deletion.CASCADE, related_name='disk', to='project_formfac.FormFactor4DFile'),
        ),
        migrations.AlterField(
            model_name='disktslicedformfactor4dfile',
            name='file',
            field=models.OneToOneField(help_text='The file meta information.', on_delete=django.db.models.deletion.CASCADE, related_name='disk', to='project_formfac.TSlicedFormFactor4DFile'),
        ),
        migrations.AlterField(
            model_name='disktslicedsaveragedformfactor4dfile',
            name='file',
            field=models.OneToOneField(help_text='The file meta information.', on_delete=django.db.models.deletion.CASCADE, related_name='disk', to='project_formfac.TSlicedSAveragedFormFactor4DFile'),
        ),
        migrations.AlterField(
            model_name='tapeconcatenatedformfactor4dfile',
            name='file',
            field=models.OneToOneField(help_text='The file meta information.', on_delete=django.db.models.deletion.CASCADE, related_name='tape', to='project_formfac.ConcatenatedFormFactor4DFile'),
        ),
        migrations.AlterField(
            model_name='tapetslicedsaveragedformfactor4dfile',
            name='file',
            field=models.OneToOneField(help_text='The file meta information.', on_delete=django.db.models.deletion.CASCADE, related_name='tape', to='project_formfac.TSlicedSAveragedFormFactor4DFile'),
        ),
    ]
