# Generated by Django 2.2.7 on 2019-11-19 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaugeconfig', '0002_auto_20191107_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nf211',
            name='charm',
            field=models.ForeignKey(help_text='Foreign Key pointing to lattice \\(\\texttt{fermionaction}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fermionaction.FermionAction'),
        ),
        migrations.AlterField(
            model_name='nf211',
            name='config',
            field=models.PositiveSmallIntegerField(help_text='Configuration number (usually MC trajectory number)'),
        ),
        migrations.AlterField(
            model_name='nf211',
            name='gaugeaction',
            field=models.ForeignKey(help_text='Foreign Key pointing to lattice \\(\\texttt{gaugeaction}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gaugeaction.GaugeAction'),
        ),
        migrations.AlterField(
            model_name='nf211',
            name='light',
            field=models.ForeignKey(help_text='Foreign Key pointing to lattice \\(\\texttt{fermionaction}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fermionaction.FermionAction'),
        ),
        migrations.AlterField(
            model_name='nf211',
            name='mpi',
            field=models.PositiveSmallIntegerField(help_text='Pion mass in MeV', null=True),
        ),
        migrations.AlterField(
            model_name='nf211',
            name='nt',
            field=models.PositiveSmallIntegerField(help_text='Temporal length in lattice units'),
        ),
        migrations.AlterField(
            model_name='nf211',
            name='nx',
            field=models.PositiveSmallIntegerField(help_text='Spatial length in lattice units'),
        ),
        migrations.AlterField(
            model_name='nf211',
            name='ny',
            field=models.PositiveSmallIntegerField(help_text='Spatial length in lattice units'),
        ),
        migrations.AlterField(
            model_name='nf211',
            name='nz',
            field=models.PositiveSmallIntegerField(help_text='Spatial length in lattice units'),
        ),
        migrations.AlterField(
            model_name='nf211',
            name='short_tag',
            field=models.TextField(blank=True, help_text="Short name for gaugeconfig (e.g. 'a15m310')", null=True),
        ),
        migrations.AlterField(
            model_name='nf211',
            name='strange',
            field=models.ForeignKey(help_text='Foreign Key pointing to lattice \\(\\texttt{fermionaction}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fermionaction.FermionAction'),
        ),
        migrations.AlterField(
            model_name='nf211',
            name='stream',
            field=models.TextField(help_text="Stream tag for Monte Carlo (e.g. 'a')"),
        ),
    ]
