# Generated by Django 2.2.7 on 2019-11-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaugeconfig', '0003_auto_20191119_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nf211',
            name='charm',
            field=models.ForeignKey(help_text='Foreign Key pointing to lattice `fermionaction`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fermionaction.FermionAction'),
        ),
        migrations.AlterField(
            model_name='nf211',
            name='gaugeaction',
            field=models.ForeignKey(help_text='Foreign Key pointing to lattice `gaugeaction`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gaugeaction.GaugeAction'),
        ),
        migrations.AlterField(
            model_name='nf211',
            name='light',
            field=models.ForeignKey(help_text='Foreign Key pointing to lattice `fermionaction`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fermionaction.FermionAction'),
        ),
        migrations.AlterField(
            model_name='nf211',
            name='strange',
            field=models.ForeignKey(help_text='Foreign Key pointing to lattice `fermionaction`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fermionaction.FermionAction'),
        ),
    ]
