# Generated by Django 2.2.7 on 2019-11-19 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correlator', '0002_auto_20191107_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baryon2pt',
            name='propagator0',
            field=models.ForeignKey(help_text='Foreign Key to first \\(\\texttt{propagator}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryon2pt',
            name='propagator1',
            field=models.ForeignKey(help_text='Foreign Key to second \\(\\texttt{propagator}\\), and must be \\(\\leq \\texttt{propagator0}\\) (also Foreign Key)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryon2pt',
            name='propagator2',
            field=models.ForeignKey(help_text='Foreign Key to third \\(\\texttt{propagator}\\), and must be \\(\\leq \\texttt{propagator1}\\) (also Foreign Key)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryon2pt',
            name='sinkwave',
            field=models.ForeignKey(help_text='Foreign Key to sink interpolating operator \\(\\texttt{wavefunction}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
        migrations.AlterField(
            model_name='baryon2pt',
            name='sourcewave',
            field=models.ForeignKey(help_text='Foreign Key to source interpolating operator \\(\\texttt{wavefunction}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
        migrations.AlterField(
            model_name='baryonfh3pt',
            name='fhpropagator',
            field=models.ForeignKey(help_text='Foreign Key pointing to Feynman-Hellmann \\(\\texttt{propagator}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryonfh3pt',
            name='propagator0',
            field=models.ForeignKey(help_text='Foreign Key pointing to spectator \\(\\texttt{propagator}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryonfh3pt',
            name='propagator1',
            field=models.ForeignKey(help_text='Foreign Key pointing to spectator \\(\\texttt{propagator}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryonfh3pt',
            name='sinkwave',
            field=models.ForeignKey(help_text='Foreign Key pointing to sink operator \\(\\texttt{wavefunction}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
        migrations.AlterField(
            model_name='baryonfh3pt',
            name='sourcewave',
            field=models.ForeignKey(help_text='Foreign Key pointing to source operator \\(\\texttt{wavefunction}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
        migrations.AlterField(
            model_name='baryonseq3pt',
            name='current',
            field=models.ForeignKey(help_text='Foreign Key to current interaction operator \\(\\texttt{wavefunction}\\)', on_delete=django.db.models.deletion.CASCADE, to='current.Current'),
        ),
        migrations.AlterField(
            model_name='baryonseq3pt',
            name='propagator',
            field=models.ForeignKey(help_text='Foreign Key pointing to daughter quark \\(\\texttt{propagator}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryonseq3pt',
            name='seqpropagator',
            field=models.ForeignKey(help_text='Foreign Key pointing to sequential \\(\\texttt{propagator}\\) (2 spectator quarks + 1 daughter)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryonseq3pt',
            name='sourcewave',
            field=models.ForeignKey(help_text='Foreign Key pointing to source operator \\(\\texttt{wavefunction}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
        migrations.AlterField(
            model_name='dwftuning',
            name='propagator',
            field=models.ForeignKey(help_text='Foreign Key to \\(\\texttt{propagator}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='dwftuning',
            name='sink5',
            field=models.BooleanField(help_text='Is the sink on the domain wall?'),
        ),
        migrations.AlterField(
            model_name='dwftuning',
            name='wave',
            field=models.ForeignKey(help_text='Foreign Key to source spin color space \\(\\texttt{wavefunction}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
        migrations.AlterField(
            model_name='meson2pt',
            name='propagator0',
            field=models.ForeignKey(help_text='Foreign Key to first \\(\\texttt{propagator}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='meson2pt',
            name='propagator1',
            field=models.ForeignKey(help_text='Foreign Key to second \\(\\texttt{propagator}\\), and must be \\(\\leq \\texttt{propagator0}\\) (also Foreign Key)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='meson2pt',
            name='sinkwave',
            field=models.ForeignKey(help_text='Foreign Key to sink interpolating operator \\(\\texttt{wavefunction}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
        migrations.AlterField(
            model_name='meson2pt',
            name='sourcewave',
            field=models.ForeignKey(help_text='Foreign Key to source interpolating operator \\(\\texttt{wavefunction}\\)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
    ]
