# Generated by Django 2.2.7 on 2019-11-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correlator', '0003_auto_20191119_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baryon2pt',
            name='propagator0',
            field=models.ForeignKey(help_text='Foreign Key to first `propagator`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryon2pt',
            name='propagator1',
            field=models.ForeignKey(help_text='Foreign Key to second `propagator`, and must be \\(\\leq\\) `propagator0` (also Foreign Key)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryon2pt',
            name='propagator2',
            field=models.ForeignKey(help_text='Foreign Key to third `propagator`, and must be \\(\\leq\\) `propagator1` (also Foreign Key)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryon2pt',
            name='sinkwave',
            field=models.ForeignKey(help_text='Foreign Key to sink interpolating operator `wavefunction`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
        migrations.AlterField(
            model_name='baryon2pt',
            name='sourcewave',
            field=models.ForeignKey(help_text='Foreign Key to source interpolating operator `wavefunction`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
        migrations.AlterField(
            model_name='baryonfh3pt',
            name='fhpropagator',
            field=models.ForeignKey(help_text='Foreign Key pointing to Feynman-Hellmann `propagator`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryonfh3pt',
            name='propagator0',
            field=models.ForeignKey(help_text='Foreign Key pointing to spectator `propagator`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryonfh3pt',
            name='propagator1',
            field=models.ForeignKey(help_text='Foreign Key pointing to spectator `propagator`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryonfh3pt',
            name='sinkwave',
            field=models.ForeignKey(help_text='Foreign Key pointing to sink operator `wavefunction`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
        migrations.AlterField(
            model_name='baryonfh3pt',
            name='sourcewave',
            field=models.ForeignKey(help_text='Foreign Key pointing to source operator `wavefunction`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
        migrations.AlterField(
            model_name='baryonseq3pt',
            name='current',
            field=models.ForeignKey(help_text='Foreign Key to current interaction operator `wavefunction`', on_delete=django.db.models.deletion.CASCADE, to='current.Current'),
        ),
        migrations.AlterField(
            model_name='baryonseq3pt',
            name='propagator',
            field=models.ForeignKey(help_text='Foreign Key pointing to daughter quark `propagator`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryonseq3pt',
            name='seqpropagator',
            field=models.ForeignKey(help_text='Foreign Key pointing to sequential `propagator` (2 spectator quarks + 1 daughter)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='baryonseq3pt',
            name='sourcewave',
            field=models.ForeignKey(help_text='Foreign Key pointing to source operator `wavefunction`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
        migrations.AlterField(
            model_name='dwftuning',
            name='propagator',
            field=models.ForeignKey(help_text='Foreign Key to `propagator`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='dwftuning',
            name='wave',
            field=models.ForeignKey(help_text='Foreign Key to source spin color space `wavefunction`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
        migrations.AlterField(
            model_name='meson2pt',
            name='propagator0',
            field=models.ForeignKey(help_text='Foreign Key to first `propagator`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='meson2pt',
            name='propagator1',
            field=models.ForeignKey(help_text='Foreign Key to second `propagator`, and must be \\(\\leq\\) `propagator0` (also Foreign Key)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
        migrations.AlterField(
            model_name='meson2pt',
            name='sinkwave',
            field=models.ForeignKey(help_text='Foreign Key to sink interpolating operator `wavefunction`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
        migrations.AlterField(
            model_name='meson2pt',
            name='sourcewave',
            field=models.ForeignKey(help_text='Foreign Key to source interpolating operator `wavefunction`', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wavefunction.SCSWaveFunction'),
        ),
    ]
