# Generated by Django 2.2.7 on 2019-11-25 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correlator', '0005_remove_correlator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baryonfh3pt',
            name='propagator1',
            field=models.ForeignKey(help_text='Foreign Key pointing to spectator `propagator` where propagator0.id <= propagator1.id is a constraint', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator'),
        ),
    ]
