# Generated by Django 2.2.7 on 2020-02-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlator', '0006_auto_20191125_2326'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='baryonseq3pt',
            name='unique_correlator_baryonseq3pt',
        ),
        migrations.RemoveField(
            model_name='baryonseq3pt',
            name='sourcewave',
        ),
        migrations.AddConstraint(
            model_name='baryonseq3pt',
            constraint=models.UniqueConstraint(fields=('current', 'seqpropagator', 'propagator'), name='unique_correlator_baryonseq3pt'),
        ),
    ]
