on:
  push:
    branches:
      - master

jobs:
    deploy-image:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Docker login
            run: echo ${{ secrets.SPIN_TOKEN }} | docker login registry.spin.nersc.gov/lattedb/lattedb -u ${{ secrets.SPIN_USERNAME }} --password-stdin
          - name: Build
            run: docker build -t lattedb .
          - name: Tag
            run: |
                docker tag lattedb registry.spin.nersc.gov/lattedb/lattedb:${{ github.sha }}
                docker tag lattedb registry.spin.nersc.gov/lattedb/lattedb:latest
          - name: Push
            run: |
                docker push registry.spin.nersc.gov/lattedb/lattedb:${{ github.sha }}
                docker push registry.spin.nersc.gov/lattedb/lattedb:latest
